name: 'personal-finance-tracker'
services:
  backend:
    image: '765430960003.dkr.ecr.us-east-1.amazonaws.com/personal-finance-tracker:pft-server'
    mem_limit: 128m
    hostname: api
    environment:
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
      - PLAID_CLIENT_ID=$PLAID_CLIENT_ID
      - PLAID_SECRET=$PLAID_SECRET
      - PLAID_ENV=$PLAID_ENV
  frontend:
    image: '765430960003.dkr.ecr.us-east-1.amazonaws.com/personal-finance-tracker:pft-client'
    mem_limit: 128m
    hostname: client
  nginx:
    image: '765430960003.dkr.ecr.us-east-1.amazonaws.com/personal-finance-tracker:pft-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
