name: 'personal-finance-tracker'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/finance_tracker
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
